VERILOG = ../src/adc.v ../src/address_decode.v ../src/ALU.v ../src/bbc.v \
	  ../src/beeb.v ../src/clocks.v ../src/cpu.v \
	  ../src/keyboard.v ../src/m6522.v ../src/mc6845.v ../src/ps2_intf.v \
	  ../src/pwm_dac.v ../src/saa5050_rom.v ../src/saa5050.v ../src/vidproc.v \
	  ../src/sn76489.v ../src/tone_generator.v ../src/mist_scandoubler.v \
	  ../src/flashmem.v ../src/ram.v pll.v 

include ulx3s.mk

